### ISSUE TITLE
Map properties are not permitted in other rules

### ISSUE THREAD

**Issue by fpauser** [mapbox/carto#397]
`node -v` => v0.12.7
`carto -v` => carto 0.14.1 (Carto map stylesheet compiler)

style.mss:
````
Map {
  background-color: #fff;
}
````

Running `carto style.mss` in the console gives me the following error:
````
Error: style.mss:2:2 Map properties are not permitted in other rules
    at Object.env.error (/home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/parser.js:235:55)
    at Definition.tree.Definition.symbolizersToXML (/home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/tree/definition.js:126:43)
    at Definition.tree.Definition.toXML (/home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/tree/definition.js:200:29)
    at /home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/tree/style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (/home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/tree/style.js:30:29)
    at Renderer.render [as renderMSS] (/home/fpauser/.node-packages/lib/node_modules/carto/lib/carto/renderer.js:54:32)
    at compileMSS (/home/fpauser/.node-packages/lib/node_modules/carto/bin/carto:102:31)
    at Object.<anonymous> (/home/fpauser/.node-packages/lib/node_modules/carto/bin/carto:159:5)
    at Module._compile (module.js:460:26)
````

What am I doing wrong?

**Comment by tartakynov** [comment]
the same issue on v0.15.2

**Comment by nebulon42** [comment]
The Map element cannot be used with direct MSS input but only with a MML file, because it would be converted to a MapSymbolizer element (which doesn't exist).
