### ISSUE TITLE
carto v0.15.0 "shield-repeat-distance" convert error

### ISSUE THREAD

**Issue by vanillycpp** [mapbox/carto#402]
I have installed carto v0.15.0, with ```--build-from-soure```
and tryed to convert my project
then got this error
```
[Error: function (data) {
      return render.call(this, data, _);
    }
function (data) {
      return render.call(this, data, _);
    }]
Error: function (data) {
      return render.call(this, data, _);
    }
function (data) {
      return render.call(this, data, _);
    }
    at Object.env.error (/usr/lib/nodejs/carto/lib/carto/parser.js:235:55)
    at Rule.tree.Rule.toXML (/usr/lib/nodejs/carto/lib/carto/tree/rule.js:56:20)
    at Definition.tree.Definition.symbolizersToXML (/usr/lib/nodejs/carto/lib/carto/tree/definition.js:137:46)
    at Definition.tree.Definition.toXML (/usr/lib/nodejs/carto/lib/carto/tree/definition.js:198:29)
    at /usr/lib/nodejs/carto/lib/carto/tree/style.js:28:27
    at Array.map (native)
    at Object.tree.StyleXML (/usr/lib/nodejs/carto/lib/carto/tree/style.js:27:29)
    at Renderer.render (/usr/lib/nodejs/carto/lib/carto/renderer.js:133:39)
    at compileMML (/usr/lib/nodejs/carto/bin/carto:74:18)
    at Object.<anonymous> (/usr/lib/nodejs/carto/bin/carto:170:9)
```
This error appires when I changing ```shield-min-distance``` into ```shield-repeat-distance``` option.
The part of code is:
```
...
#roads_label_sheild[type!='secondary'][zoom>=9][zoom<=14][reflen<=8] {
  shield-name: "[ref]";
  shield-size: 9;
  shield-face-name: @sans_bold;
  shield-fill: #fff;
  shield-file: url(img/shield-motorway-1.png); 

  [type='trunk'], 
  [type='primary'], 
  [type='secondary'] { 
    shield-file: url("img/shield-trunk-[reflen]n.png");
  }   
 
  [type='motorway'],
  [type='trunk']{
    [zoom=9] { shield-repeat-distance: 230; }  
  }  
}
...
```
I also tried to add this ```shield-placement:line;``` option, with no result

my previos ```carto``` convers this with no error, and ```tilemill``` works with this code well!

**Comment by vanillycpp** [comment]
It was my mistake I have found command `carto -v` and got that my version of carto is `0.9...`
so, I reinstalled carto and problem was gone
