### ISSUE TITLE
TypeError: Object #<Object> has no method 'load'

### ISSUE THREAD

**Issue by strk** [mapbox/carto#428]
I've just pulled master (21be5fb8d5643d70ff48a1c3249d8b4f9f2ddb09) and run `npm test`
The result:
```
 carto@0.15.3 test /usr/src/node/modules/carto
> mocha -R spec


/usr/src/node/modules/carto/lib/carto/tree/reference.js:27
    ref.setData(mapnik_reference.load(version));
                                 ^
TypeError: Object #<Object> has no method 'load'
    at Object.ref.setVersion (/usr/src/node/modules/carto/lib/carto/tree/reference.js:27:34)
    at Renderer.render (/usr/src/node/modules/carto/lib/carto/renderer.js:78:26)
    at Object.<anonymous> (/usr/src/node/modules/carto/test/bug181.js:10:46)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/src/node/modules/carto/node_modules.symlink/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/src/node/modules/carto/node_modules.symlink/mocha/lib/mocha.js:149:14)
    at Mocha.run (/usr/src/node/modules/carto/node_modules.symlink/mocha/lib/mocha.js:306:31)
    at Object.<anonymous> (/usr/src/node/modules/carto/node_modules.symlink/mocha/bin/_mocha:343:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

node.js version is v0.10.26
npm version is 1.4.3

**Comment by strk** [comment]
Closing as invalid, my node_modules were not in sync with expected
