### ISSUE TITLE
npm test: Invalid value for raster-mode

### ISSUE THREAD

**Issue by strk** [mapbox/carto#429]
commit 21be5fb8d5643d70ff48a1c3249d8b4f9f2ddb09
npm install from scratch
npm test output:
```
> carto@0.15.3 test /usr/src/node/modules/carto
> mocha -R spec


/usr/src/node/modules/carto/lib/carto/renderer.js:148
    if (env.errors) throw env.errors;
                             ^
Error: :1:5 Invalid value for raster-mode, the type keyword (options: normal, grain_merge, grain_merge2, multiply, multiply2, divide, divide2, screen, hard_light) is expected. normal (of type string)  was given.
    at Object.env.error (/usr/src/node/modules/carto/lib/carto/parser.js:235:55)
    at Rule.tree.Rule.toXML (/usr/src/node/modules/carto/lib/carto/tree/rule.js:83:24)
    at Definition.tree.Definition.symbolizersToXML (/usr/src/node/modules/carto/lib/carto/tree/definition.js:139:46)
    at Definition.tree.Definition.toXML (/usr/src/node/modules/carto/lib/carto/tree/definition.js:200:29)
    at /usr/src/node/modules/carto/lib/carto/tree/style.js:31:27
    at Array.map (native)
    at Object.tree.StyleXML (/usr/src/node/modules/carto/lib/carto/tree/style.js:30:29)
    at Renderer.render (/usr/src/node/modules/carto/lib/carto/renderer.js:130:39)
    at Object.<anonymous> (/usr/src/node/modules/carto/test/bug181.js:10:46)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/src/node/modules/carto/node_modules/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/src/node/modules/carto/node_modules/mocha/lib/mocha.js:149:14)
    at Mocha.run (/usr/src/node/modules/carto/node_modules/mocha/lib/mocha.js:306:31)
    at Object.<anonymous> (/usr/src/node/modules/carto/node_modules/mocha/bin/_mocha:343:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by strk** [comment]
npm ls:
```
carto@0.15.3 /usr/src/node/modules/carto
├─┬ coveralls@2.10.1
│ ├─┬ js-yaml@3.0.1
│ │ ├─┬ argparse@0.1.16
│ │ │ ├── underscore@1.7.0
│ │ │ └── underscore.string@2.4.0
│ │ └── esprima@1.0.4
│ ├── lcov-parse@0.0.6
│ ├── log-driver@1.2.4
│ └─┬ request@2.16.2
│   ├── aws-sign@0.2.0
│   ├── cookie-jar@0.2.0
│   ├── forever-agent@0.2.0
│   ├─┬ form-data@0.0.10
│   │ ├── async@0.2.10
│   │ └─┬ combined-stream@0.0.7
│   │   └── delayed-stream@0.0.5
│   ├─┬ hawk@0.10.2
│   │ ├── boom@0.3.8
│   │ ├── cryptiles@0.1.3
│   │ ├── hoek@0.7.6
│   │ └── sntp@0.1.4
│   ├── json-stringify-safe@3.0.0
│   ├── mime@1.2.11
│   ├── node-uuid@1.4.7
│   ├── oauth-sign@0.2.0
│   ├── qs@0.5.6
│   └── tunnel-agent@0.2.0
├─┬ istanbul@0.2.16
│ ├── abbrev@1.0.7
│ ├── async@0.9.2
│ ├─┬ escodegen@1.3.3
│ │ ├── esprima@1.1.1
│ │ ├── estraverse@1.5.1
│ │ ├── esutils@1.0.0
│ │ └─┬ source-map@0.1.43
│ │   └── amdefine@1.0.0
│ ├── esprima@1.2.5
│ ├─┬ fileset@0.1.8
│ │ ├─┬ glob@3.2.11
│ │ │ ├── inherits@2.0.1
│ │ │ └─┬ minimatch@0.3.0
│ │ │   ├── lru-cache@2.7.3
│ │ │   └── sigmund@1.0.1
│ │ └─┬ minimatch@0.4.0
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├─┬ handlebars@1.3.0
│ │ ├── optimist@0.3.7
│ │ └─┬ uglify-js@2.3.6
│ │   ├── async@0.2.10
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.0
│ ├─┬ js-yaml@3.5.3
│ │ ├─┬ argparse@1.0.6
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@2.7.2
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── nopt@3.0.6
│ ├── resolve@0.7.4
│ ├── which@1.0.9
│ └── wordwrap@0.0.3
├─┬ jshint@0.2.3
│ └── argsparser@0.0.7
├── mapnik-reference@8.5.2
├─┬ mocha@1.12.1
│ ├── commander@0.6.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── diff@1.0.2
│ ├─┬ glob@3.2.1
│ │ ├── graceful-fs@1.2.3
│ │ ├── inherits@1.0.2
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.7.0
│ ├─┬ jade@0.26.3
│ │ └── mkdirp@0.3.0
│ └── mkdirp@0.3.5
├─┬ optimist@0.6.1
│ ├── minimist@0.0.10
│ └── wordwrap@0.0.3
├── sax@0.1.5
└── underscore@1.8.3
```

node v0.10.26
npm 1.4.3

**Comment by nebulon42** [comment]
I tried reproducing your problem, but was not able to on Linux x64 with Node v0.10.26 and NPM 1.4.3 (used for testing purposes). My normal setup is v4.3.1.

**Comment by nebulon42** [comment]
closing per comment above.
